- name: My first play
  hosts: all
  gather_facts: false
  tasks:
    - name: determine hosts that are up
      ignore_unreachable: 'yes'
      wait_for_connection:
        timeout: 10
      register: ping_result
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
- name: Classify hosts based on task result
  hosts: all
  tasks:
    - name: Move successful hosts to successful group
      add_host:
        name: '{{ inventory_hostname }}'
        groups: successful
      when: ping_result is succeeded
    - name: Move failed hosts to failed group
      add_host:
        name: '{{ inventory_hostname }}'
        groups: failed
      when: ping_result is failed
