- name: My first play
  hosts: failed_hosts
  gather_facts: false
  tasks:
   - name: Ping my hosts
     block:
      - name: determine hosts that are up
        ignore_unreachable: yes
        wait_for_connection:
          timeout: 10
      - name: Print message
        ansible.builtin.debug:
          msg: Hello world
     rescue:
       - name: create host group for failed host
         group_by:
           key: "failed_hosts"
