- name: My first play
  hosts: all
  gather_facts: false
  tasks:
    - name: ping
      when: "'successful' not in group_names"
      block:
        - name: determine hosts that are up
          ignore_unreachable: 'yes'
          wait_for_connection:
            timeout: 10
          register: ping_result
        - name: Print message
          ansible.builtin.debug:
            msg: Hello world
      rescue:
         - name: Set fact
           when: ping_result is failed
           set_fact: pinged="true"
  
