- name: My first play
  hosts: all
  gather_facts: false
  tasks:
    - name: ping
      when: "'successful' not in group_names"
      block:
        - name: determine hosts that are up
          ignore_unreachable: 'yes'
          wait_for_connection:
            timeout: 10
          register: ping_result
        - name: Print message
          ansible.builtin.debug:
            msg: Hello world
      rescue:
         - name: Create Inventory
           when: ping_result is succeeded
           tower_inventory:
             name: "Foo Inventory"
             description: "Our Foo Cloud Servers"
             organization: "Default"
             state: present
         - name: Create Group
           when: ping_result is succeeded
           tower_group: 
             inventory: "Foo Inventory" 
             name:  Testes 
           register: fs_group 
         - name: Create Host
           when: ping_result is succeeded
           tower_host:
             inventory: "Successful hosts" 
             name: "host"  
           register: fs_host 
         - name: Associate host group 
           when: ping_result is succeeded
           shell: tower-cli host associate  --host "{{fs_host.id}}" --group "> {{fs_group.id}}"
  
