- name: My first play
  hosts: all
  tasks:
   - name: Ping my hosts
     block:
      - name: determine hosts that are up
        wait_for_connection:
          timeout: 10
     rescue:
       - name: create host group for failed host
         group_by:
           key: "failed_hosts"
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
