- name: My first play
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
     ignore_unreachable: yes
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
